url: https://bobstring.github.io/
baseurl: 

# Site settings
title: Roberto Martin Munoz
email: contact@robertmm.com
description: "Welcome to my personal web page. Were you will find my career and my personal project, enjoy!"
google-tracking-id: "UA-59793434-2"
force-https: True

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

#About variables
me-img: "./img/bob.jpg"

pages_list:
  - text: "About"
    link: "#about"
  - text: "Career"
    link: "#career"
  - text: "Volunteer"
    link: "#volunteer"
  - text: "Portfolio"
    link: "#portfolio"
  - text: "Contact"
    link: "#contact"
  - text: "Download my CV"
    link: "./docs/RobertoMartin.pdf"

# Career variables

# First image of the Career timeline
career-img: "./img/rorodroid.png"

events:
  - image: "./img/timeline/talkspace.png"
    date: "February 2016 - Today"
    title: "Android Engineer @ <a href='http://www.talkspace.com/'>Talkspace</a>"
    description: "Responsible for designing, developing, and maintaining Android applications."
  - image: "./img/timeline/tad.png"
    date: "April 2013 - January 2016"
    title: "Android developer @ <a href='https://www.timeanddate.com/'>Time And Date AS</a>"
    description: "Responsible for designing, developing, and maintaining Android applications. <a href='https://play.google.com/store/apps/dev?id=8352391058331202125'>Apps link</a> "
  - image: "./img/timeline/uis.png"
    date: "January 2013 - June 2014"
    title: "<a href='http://www.uis.no/studies/master-s-programmes-in-english/computer-science/'> MSc of Information Technology @ Universitetet i Stavanger , Norway</a>"
    description: "Web semantic technologies, wireless communications and security in networks."
  - image: "./img/timeline/uis.png"
    date: "August 2012 - June 2014"
    title: "Student Assistant @ Universitetet i Stavanger , Norway"
    description: "Part time team member of European Union funded project Self learning Energy Efficient Buildings and Open Spaces (<a href='http://seeds-fp7.eu/partners.php'>SEEDS</a>). Technologies used: Java, Bash"
  - image: "./img/timeline/zaizi.png"
    date: "April 2012 - July 2012"
    title: "Software Developer Intership @ <a href='http://www.zaizi.com/'>Zaizi Iberia</a> in Seville, Spain"
    description: "3 month intership where I learned how to work with and develop tools for the CMS Alfresco. Analysed and deployed a semantic tool (Apache Stanbol) to integrate into Alfresco."
  - image: "./img/timeline/us.png"
    date: "September 2008 - July 2014"
    title: "<a href='https://www.informatica.us.es/index.php/plan-del-97/ingenieria-informatica/asignaturas-ii'> Computer Science Engineering degree @ University of Seville, Spain</a>"
    description: "Engineering degree where is taught the  methodology, tools and techniques, and theory of computer science, from low level hardware to high level programming"

# Volunteer experience, if more than 2 change to col-md-4 in volunteer.html 
volunteer:
  - image: "./img/volunteer/cert.png"
    title: "Highland Park CERT"
    date: "June 2015 - Today"
    description: "The Community Emergency Response Team program educates people about disaster preparedness for hazards that may impact their area and trains them in basic disaster response skills, such as fire safety, light search and rescue, team organization, and disaster medical operations."
  - image: "./img/volunteer/cfp.png"
    title: "Development Lead in Code For Princeton"
    date: "July 2015 - Today"
    description: "In <a href='http://codeforprinceton.org/about-3/'> Code for Princeton </a> we host hack nights, workshops, and talks plus work with the municipal government to provide open datasets. We are part of the <a href='http://www.codeforamerica.org/'>Code for America</a> Brigade Network."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/BobString
  - title: linkedin 
    url: https://www.linkedin.com/in/robertomm
  - title: github
    url: https://github.com/BobString


# Build settings
markdown: kramdown
permalink: pretty
